"""Temporary manual integration check for the OpenAI ranking provider."""

__test__ = False

from app.models import SearchRequest, VehicleListing
from app.services.openai_ranking import OpenAIRankingService


def main() -> None:
    search_request = SearchRequest(
        make="Honda",
        model="CR-V",
        min_year=2019,
        max_year=2024,
        max_price=30000,
        max_mileage=60000,
        location="Austin, TX",
    )

    listings = [
        VehicleListing(
            vin="1HNYD1860X0000001",
            year=2023,
            make="Honda",
            model="CR-V",
            trim="EX-L",
            body_style="SUV",
            drivetrain="AWD",
            engine="1.5L Turbo",
            transmission="CVT",
            exterior_color="Modern Steel Metallic",
            fuel="Gasoline",
            price=28900,
            mileage=18000,
            city="Austin",
            state="TX",
            zip="78701",
            dealer="Capital Honda",
            accident_count=0,
            has_accidents=False,
            owner_count=1,
            one_owner=True,
            usage_type="Personal",
        ),
        VehicleListing(
            vin="1HNYD1860X0000002",
            year=2021,
            make="Honda",
            model="CR-V",
            trim="EX",
            body_style="SUV",
            drivetrain="AWD",
            engine="1.5L Turbo",
            transmission="CVT",
            exterior_color="Platinum White",
            fuel="Gasoline",
            price=24500,
            mileage=42000,
            city="Round Rock",
            state="TX",
            zip="78664",
            dealer="North Austin Motors",
            accident_count=0,
            has_accidents=False,
            owner_count=2,
            one_owner=False,
            usage_type="Personal",
        ),
        VehicleListing(
            vin="1HNYD1860X0000003",
            year=2020,
            make="Honda",
            model="CR-V",
            trim="LX",
            body_style="SUV",
            drivetrain="FWD",
            engine="2.4L",
            transmission="CVT",
            exterior_color="Crystal Black",
            fuel="Gasoline",
            price=21900,
            mileage=58000,
            city="Pflugerville",
            state="TX",
            zip="78660",
            dealer="Lone Star Auto",
            accident_count=1,
            has_accidents=True,
            owner_count=2,
            one_owner=False,
            usage_type="Personal",
        ),
        VehicleListing(
            vin="1HNYD1860X0000004",
            year=2024,
            make="Honda",
            model="CR-V",
            trim="Sport Touring",
            body_style="SUV",
            drivetrain="AWD",
            engine="2.0L Hybrid",
            transmission="E-CVT",
            exterior_color="Radiant Red",
            fuel="Hybrid",
            price=33900,
            mileage=9000,
            city="Cedar Park",
            state="TX",
            zip="78613",
            dealer="Hill Country Honda",
            accident_count=0,
            has_accidents=False,
            owner_count=1,
            one_owner=True,
            usage_type="Personal",
        ),
        VehicleListing(
            vin="1HNYD1860X0000005",
            year=2019,
            make="Honda",
            model="CR-V",
            trim="Touring",
            body_style="SUV",
            drivetrain="AWD",
            engine="1.5L Turbo",
            transmission="CVT",
            exterior_color="Lunar Silver",
            fuel="Gasoline",
            price=19900,
            mileage=74000,
            city="Georgetown",
            state="TX",
            zip="78626",
            dealer="Georgetown Auto Group",
            accident_count=2,
            has_accidents=True,
            owner_count=3,
            one_owner=False,
            usage_type="Rental",
        ),
    ]

    result = OpenAIRankingService().rank_listings(search_request, listings)
    for ranking in result.rankings:
        print(f"Rank {ranking.rank}: {ranking.vin} | Score {ranking.score}")
        print(f"Reason: {ranking.reason}")


if __name__ == "__main__":
    main()
